/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen (and enhanced with Prixtara domain types).
 * Command: `pnpm --filter @prixtara/cms typegen`
 * ---------------------------------------------------------------------------------
 */

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: {
    dimensions?: {
      height: number;
      width: number;
      aspectRatio: number;
    };
  };
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  url?: string;
  size?: number;
};

// Object Types
export type SanitySeo = {
  _type: 'seo';
  metaTitle?: string;
  metaDescription?: string;
  canonicalUrl?: string;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
  };
  noindex?: boolean;
  structuredData?: {
    schemaType?: string;
    jsonLdRaw?: string;
  };
};

export type SanityCaptionedImage = {
  _type: 'captionedImage';
  asset?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
  };
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  altText?: string;
  caption?: string;
  credit?: string;
};

export type SanityVideoMedia = {
  _type: 'videoMedia';
  title?: string;
  videoFile?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
    };
  };
  externalUrl?: string;
  posterImage?: SanityCaptionedImage;
  autoPlay?: boolean;
  loop?: boolean;
};

export type SanityCta = {
  _type: 'cta';
  label: string;
  linkType: 'internal' | 'external';
  internalPath?: string;
  externalUrl?: string;
  variant?: 'primary' | 'secondary' | 'outline' | 'ghost';
  openInNewTab?: boolean;
};

export type SanitySocialLink = {
  _type: 'socialLink';
  platform: 'linkedin' | 'x' | 'github' | 'youtube' | 'instagram' | 'discord' | 'other';
  label: string;
  url: string;
};

export type SanityNavItem = {
  _type: 'navItem';
  label: string;
  description?: string;
  linkType: 'internal' | 'external';
  internalPath?: string;
  externalUrl?: string;
  openInNewTab?: boolean;
  badge?: string;
  children?: Array<{
    _key: string;
    label: string;
    description?: string;
    path: string;
    isExternal?: boolean;
  }>;
};

export type SanityMetricItem = {
  _type: 'metricItem';
  value: string;
  unit?: string;
  label: string;
  context?: string;
  highlight?: boolean;
};

export type SanityPrincipleItem = {
  _type: 'principleItem';
  number?: string;
  title: string;
  description: string;
  impact?: string;
};

export type SanityMilestoneItem = {
  _type: 'milestoneItem';
  yearOrDate: string;
  title: string;
  description: string;
  highlight?: boolean;
};

export type SanityTeamMember = {
  _type: 'teamMember';
  name: string;
  role: string;
  bio?: string;
  image?: SanityCaptionedImage;
  socialLinks?: Array<SanitySocialLink & { _key: string }>;
};

export type SanityBenefitItem = {
  _type: 'benefitItem';
  title: string;
  description: string;
  category?: string;
  iconName?: string;
};

export type SanityTechnicalSpecItem = {
  _type: 'technicalSpecItem';
  label: string;
  value: string;
  description?: string;
};

export type SanityTechnicalSpecGroup = {
  _type: 'technicalSpecGroup';
  category: string;
  items: Array<SanityTechnicalSpecItem & { _key: string }>;
};

export type SanityCapabilityItem = {
  _type: 'capabilityItem';
  title: string;
  description: string;
  badge?: string;
  metricsSummary?: string;
};

// Section Types
export type SanityHeroSection = {
  _key: string;
  _type: 'heroSection';
  headline: string;
  subheadline?: string;
  tagline?: string;
  primaryCta?: SanityCta;
  secondaryCta?: SanityCta;
  backgroundVideo?: SanityVideoMedia;
  backgroundImage?: SanityCaptionedImage;
  badges?: string[];
};

export type SanityProductsSection = {
  _key: string;
  _type: 'productsSection';
  sectionTitle: string;
  sectionSubtitle?: string;
  displayMode: 'all' | 'manual';
  curatedProducts?: Array<{
    _ref: string;
    _type: 'reference';
    _key: string;
  }>;
  viewAllCta?: SanityCta;
};

export type SanityVisionSection = {
  _key: string;
  _type: 'visionSection';
  eyebrow?: string;
  headline: string;
  description?: string;
  principles?: Array<SanityPrincipleItem & { _key: string }>;
  featuredMedia?: SanityCaptionedImage;
  cta?: SanityCta;
};

export type SanityMetricsSection = {
  _key: string;
  _type: 'metricsSection';
  sectionTitle: string;
  sectionSubtitle?: string;
  metrics: Array<SanityMetricItem & { _key: string }>;
};

export type SanityTechThemesSection = {
  _key: string;
  _type: 'techThemesSection';
  sectionTitle: string;
  sectionDescription?: string;
  themes?: Array<{
    _key: string;
    title: string;
    description: string;
    badge?: string;
    iconName?: string;
  }>;
};

export type SanityProcessSection = {
  _key: string;
  _type: 'processSection';
  sectionTitle: string;
  sectionDescription?: string;
  steps: Array<{
    _key: string;
    stepNumber: number;
    title: string;
    description: string;
    duration?: string;
  }>;
};

export type SanityCtaSection = {
  _key: string;
  _type: 'ctaSection';
  headline: string;
  description?: string;
  primaryCta: SanityCta;
  secondaryCta?: SanityCta;
};

export type SanityTestimonialsSection = {
  _key: string;
  _type: 'testimonialsSection';
  sectionTitle?: string;
  quotes?: Array<{
    _key: string;
    quote: string;
    author: string;
    role?: string;
    organization?: string;
    avatar?: SanityCaptionedImage;
  }>;
};

export type SanitySectionBlock =
  | SanityHeroSection
  | SanityProductsSection
  | SanityVisionSection
  | SanityMetricsSection
  | SanityTechThemesSection
  | SanityProcessSection
  | SanityCtaSection
  | SanityTestimonialsSection;

// Document Types
export type SanitySiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  companyName: string;
  logo?: SanityCaptionedImage;
  logoDark?: SanityCaptionedImage;
  favicon?: { asset?: { _ref: string } };
  primaryContact?: {
    email?: string;
    supportEmail?: string;
    phone?: string;
    address?: string;
    officeHours?: string;
  };
  socialLinks?: Array<SanitySocialLink & { _key: string }>;
  defaultSeo?: SanitySeo;
  defaultOgImage?: SanityCaptionedImage;
  footer?: {
    copyrightText?: string;
    tagline?: string;
    disclaimer?: string;
    legalLinks?: Array<{
      _key: string;
      label: string;
      href: string;
      isExternal?: boolean;
    }>;
  };
};

export type SanityNavigation = {
  _id: string;
  _type: 'navigation';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  primaryNavigation: Array<SanityNavItem & { _key: string }>;
  cta?: SanityCta;
  footerNavigation: Array<{
    _key: string;
    columnTitle: string;
    links: Array<{
      _key: string;
      label: string;
      href: string;
      isExternal?: boolean;
      badge?: string;
    }>;
  }>;
  externalLinks?: Array<{
    _key: string;
    label: string;
    url: string;
    description?: string;
    openInNewTab?: boolean;
  }>;
};

export type SanityHomepage = {
  _id: string;
  _type: 'homepage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  sections: SanitySectionBlock[];
  seo?: SanitySeo;
};

export type SanityProduct = {
  _id: string;
  _type: 'product';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: { _type: 'slug'; current: string };
  productCategory: string;
  shortDescription: string;
  longDescription?: unknown;
  thumbnail: SanityCaptionedImage;
  heroMedia?: {
    mediaType: 'image' | 'video';
    image?: SanityCaptionedImage;
    video?: SanityVideoMedia;
  };
  gallery?: Array<SanityCaptionedImage & { _key: string }>;
  video?: SanityVideoMedia;
  problemStatement?: unknown;
  solution?: unknown;
  capabilities?: Array<SanityCapabilityItem & { _key: string }>;
  technicalDetails?: Array<SanityTechnicalSpecGroup & { _key: string }>;
  metrics?: Array<SanityMetricItem & { _key: string }>;
  features?: Array<{
    _key: string;
    title: string;
    description: string;
    badge?: string;
    iconName?: string;
  }>;
  useCases?: Array<{
    _key: string;
    title: string;
    targetAudience?: string;
    scenario: string;
    impact: string;
  }>;
  applications?: Array<{
    _key: string;
    industry: string;
    title: string;
    description: string;
    deploymentType?: string;
  }>;
  process?: Array<{
    _key: string;
    stepNumber: number;
    title: string;
    description: string;
    duration?: string;
  }>;
  cta?: SanityCta;
  relatedProducts?: Array<{
    _ref: string;
    _type: 'reference';
    _key: string;
  }>;
  seo?: SanitySeo;
};

export type SanityVisionPage = {
  _id: string;
  _type: 'visionPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  introduction: string;
  contentSections?: Array<{
    _key: string;
    heading: string;
    subheading?: string;
    body?: unknown;
    media?: SanityCaptionedImage;
  }>;
  principles?: Array<SanityPrincipleItem & { _key: string }>;
  technologyThemes?: Array<{
    _key: string;
    title: string;
    description: string;
    category?: string;
    tags?: string[];
  }>;
  media?: SanityCaptionedImage;
  seo?: SanitySeo;
};

export type SanityCareerPage = {
  _id: string;
  _type: 'careerPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  introHeadline?: string;
  pageContent?: unknown;
  cultureContent?: {
    headline: string;
    description?: string;
    coreValues?: Array<{
      _key: string;
      title: string;
      description: string;
    }>;
  };
  benefits?: Array<SanityBenefitItem & { _key: string }>;
  cta?: {
    headline: string;
    description?: string;
    buttonLabel: string;
    applicationEmail: string;
  };
  seo?: SanitySeo;
};

export type SanityJobPosting = {
  _id: string;
  _type: 'jobPosting';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: { _type: 'slug'; current: string };
  department: string;
  location: string;
  isRemote: boolean;
  employmentType: string;
  summary: string;
  description?: unknown;
  responsibilities: string[];
  requirements: string[];
  optionalRequirements?: string[];
  published: boolean;
  publishedAt: string;
  applicationCta?: {
    type: 'email' | 'url';
    destination: string;
    buttonText: string;
    instructions?: string;
  };
  seo?: SanitySeo;
};

export type SanityAboutPage = {
  _id: string;
  _type: 'aboutPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  tagline?: string;
  companyStory: unknown;
  mission: string;
  vision: string;
  leadership?: Array<SanityTeamMember & { _key: string }>;
  media?: SanityCaptionedImage;
  milestones?: Array<SanityMilestoneItem & { _key: string }>;
  seo?: SanitySeo;
};
